### ISSUE TITLE
Exported Windows version by Github Actions not working 

### ISSUE THREAD

**Issue by gumaciel** [sakkaku-dev/rpg-arena#1]
My computer: Windows 10 PRO 64 Bits

https://github.com/sakkaku-dev/rpg-arena/suites/1468130525/artifacts/25225773

**Comment by myin142** [comment]
I noticed this issue recently too, since I switch to dual booting Windows again. But it was never high priority. I will look into it if I have time.
I did not expect other people to test my game here. But thanks for opening an issue, I totally forgot about it.

**Comment by myin142** [comment]
The problem does not seem to be in my project. I had the same error once and the issue was the godot docker image.  (Issue: aBARICHELLO/godot-ci#31) But it seems to be an issue in godot itself.
One possible solution would be to not use class names, but I don't plan on changing the code now. I just keep that in mind for my future projects.
